### ISSUE TITLE
How to compile the project?

### ISSUE THREAD

**Issue by vsnthdev** [pedromsilvapt/clui-live#1]
There are no docs on how to compile the TypeScript code into JavaScript. Also, when running the `tsc` command: The following error occurs:
```
node_modules/@types/node/index.d.ts:80:11 - error TS2300: Duplicate identifier 'IteratorResult'.

80 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  ../../../../usr/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

../../../../usr/lib/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:80:11
    80 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.


Found 2 errors.
```

**Comment by pedromsilvapt** [comment]
Hi, sorry for the issues you've been having.

If you need to compile the project, it is pretty straigthforward, hence why I did not include any instructions. If you're using VS Code, the repo has an included `tasks.json` file so there is no need for additional configuration. Or if you prefer, you can just use `tsc` like you did inside the folder and it should all work.

Now about the errors you're facing, they seem to be an incompatibility between newer versions of the TypeScript compiler and the typing definitions I was using. I haven't compiled this project in a while (since I published it on NPM and I tend to just use that when I need it), hence why I didn't notice the errors.

They were fixed by simply updating the typings:
```typescript
npm install --save-dev @types/node
```

I've updated the repo with the aforementioned fix as well.

I hope you enjoy using this little library, and if you find any other issues or have any further questions, please let me know! :)
